package model;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import contract.IElement;

public class BoulderDashModelTest  {
//	private DwarfMiner dwarf;
//	private BrokenDirt brokenDirt;
	private BoulderDashModel model;
	IElement elements;
	ArrayList<IElement> list;
	int x = 3;
	int y = 2;
	

	@Before
	public void setUp() throws Exception {
		this.model = new BoulderDashModel();
	//	DwarfMiner dwarf = new DwarfMiner();
		this.elements=model.getElement();
	}

	@After
	public void tearDown() throws Exception {
	}


	@Test
	public void testGetHelloWorld() {
		assertNotNull(this.model.helloWorld);
	}

	@Test
	public void testLoadHelloWorld() { 
		this.model.loadHelloWorld("1");
		assertEquals("wwwwwwwwwwwwwwwwwwwwwwwwwwwwww@wrrrrrddddddddddddddddddddridw@wbbbbbddrddddddrrrrdddrdddrddw@wbbbbbdddddrddddddddddddddrddw@wcddddidddddddddddrddddrddrrrw@wddddddddddddddddddddddddddddw@wdrddddddddrdddddddddrdddddddw@wdddrdddddrddddrddddiddddddddw@wdddrdrddddddrddddddddddrddddw@wdddddddddrddddddrdddddrdddddw@wdrdddddrddddddddddddddddddddw@wddddddddddrdddrddidddrddddddw@wddrddrdrddddidddddddddrdddddw@wdddidddddddrdddrddddddddddddw@wdddrdddrdddddddddddiddrddiddw@wdddddddddrddddddrdddddrdddddw@wddrddidddrddddddddrddddrddddw@wddrdddidddddrdddddrdddddddddw@wrrrddddrdddrddddddrrrrdddrddw@wddddddddidddddddddddddddddddw@wddddiddrddddrdddiddddrddddddw@wddrdddddidddddddddddddddddddw@wddddddddddddddddrrrdddddddddw@wdddrdddddddddddddiddrdddrdddw@wddrirdddddrdddddrdddirddddddw@wwwwwwwwwwddddddddddddrrdrdddw@wdddddddrwddddddrddddddddrwwww@wdrrrrrrwwdddddddddrdddddddddw@wddddddidddddddddddidddrwbddpw@wwwwwwwwwwwwwwwwwwwwwwwwwwwwww", this.model.getHelloWorld().getMessage());
		this.model.loadHelloWorld("2");
		assertEquals("wwwwwwwwwwwwwwwwwwwwwwwwwwwww@wcdddddrdrdrirrrrrrdddddddriw@wrdddrddddddrdddddddddddddrrw@widdddrrrddddddrddddrdddrdedw@wrdddrdddddbbbddddddddddddddw@wddddddddddbebdrdrdrdddrrdddw@wrddrddddddbbbddddrdrdrddddrw@wdrrdrrrddrrdddddrdddrddddddw@wirddddrrddddddrdddddddrddddw@wddddddddrddrdddddddddddrdddw@wedrrdddddddddddddddddddiwwww@wbwwwwwwwwwwwdddwwwwwwwwwwwww@wbwrdddddddrrrirddddddddddddw@wbwidddddddddddddddrddirrrddw@wwwwwwwwwwwdrddddddidddddddww@wirrrrdddddddddddddrdddddwwww@wddddddddddddddddddddddddwirw@wwwwwwwwrwwwddddddrdrdddddddw@wrdddddddddwddrrddddddddddddw@wddwwwwwwddwddddddddddddrrrrw@wddwrrrrwddwddwdwwwwwwwddddiw@wrdwddddwdrwddwbbbbbbewwwwwdw@wddwdwddwddwddwbbbbbbiwdddddw@wdrwdwiiwddwddwbbbbbbbwdddddw@wddwdwwwwddwddwwwwwwwwwdddddw@wddwdrdrdddwddddddddddwwwwwww@wddwdddddddwrrrrrrrrrdwebpbrw@wdddwwwwwwwwddddddddddwbbbddw@wddddddddddddbbbbbbbbddbbbbiw@wwwwwwwwwwwwwwwwwwwwwwwwwwwww", this.model.getHelloWorld().getMessage());
		this.model.loadHelloWorld("3");
		assertEquals("wwwwwwwwwwwwwwwwwwwwwwwwwwwww@wcdddddddddddddddddddddrrrriw@wdwwwwwwwwwwwwwdddddddddddddw@wdwdddddddddddwwrrddddrrrdrrw@wdwddddwwwwwrdwddddwwdddddddw@wdwdrddwrrrwddwdddwwwwdwdwdww@wdwddddwddddddwdrrrrrrdwdwddw@wdwrdddwddbwwdwddddddddwdwddw@wdwdrddwddbwddwwrrrrrwdwdwddw@wdwddddwddbwdrwidddddddwdwddw@wdwirdddddewddwdddddddwwdwddw@wdwwwwdwwwwwwdwddddddrdwdwddw@wbbbbwdrdddiwbbbbbbbbrdwdwddw@wbbebwddrdddwbbbebbbbriwdwddw@wbbbiwdddrddwbbbbbbbbdwwwwwww@wwwwwdddddrdwwwddddddwbbbbbbw@wirrrdddrrrrwwwwwwwwwwbbpbbew@wddddwdddddrdddddddddwbbbbbbw@wdrrrwdddddrrdrwrrrddwbbbbbbw@wdrrrwdddddrdrrdddddrwbbbbbbw@wdrrrwdddddrddrirdrrdwdrddddw@wdddrwdwwwwrdrrdrrrdrwwdddddw@wddddwbbbbbrrwrddirdddddwwwww@wbbbbwbbebbrrrdrrrrrwwddddddw@wbbbbwbbbbbrddrddrrdwwdwddddw@wbbbbwbbbbbrddwwrddwdwddddddw@wbebbwbbebbrdddddwdddwddddddw@wbbbbwrbbbbrdddddddddwddddddw@wbbbbddbbbbdddddddddddddddddw@wwwwwwwwwwwwwwwwwwwwwwwwwwwww", this.model.getHelloWorld().getMessage());
		this.model.loadHelloWorld("4");
		assertEquals("wwwwwwwwwwwwwwwwwwwwwwwwwwwwww@wcdddddddddddddddddddbbbebbbiw@wddddddddddddddddddddbbbbebbiw@wddddddddddddddddddddbbbbbebbw@wddddddddddddddddddddbbbbbbebw@wwwwwwwwwwwwwwwwwwwwwwwwdddddw@wrddrdirddrddrddrddrddrddddddw@wdrddrddrddrddrddrddrddrdddddw@wddddddddddddddddddddddddddddw@wrddddddddrddddddddddrrrdddddw@wwwwwwwwwwwdddddddddddddddebbw@wbbbbbbbbrwdddddddddddddddbibw@wbbbbbbbbdddddddddddddddddbbbw@wbbbbbbbbwwwwwwwwwwwwwwwwwwwww@wbbbeeebbbwddddddddddddbbbpbbw@wbbbeiebbbwdddddddddddwbbbbbbw@wbbbeeebbbwdddddrrddddwbbbbbbw@wbbbbbbbbbwddddrddrdddwbbebbbw@wbbbbbbbbbwddddrdirdddwbbbbbbw@wbbbbbbbbbwddddrddrdddwbbbbbbw@wbbbbbbbbbwdddddrrddddwbbebbbw@wbbbbbbbbbwdddddddddddwbbbbbbw@wwwwwwddddwdddddddddddwddbbddw@wdrrrrrrrdwrrrrdddddddwbbebbbw@wdddddddddwrdddrddddddwbbbbbbw@wdbbbbbbbdddrdddrdddddwbbebbbw@wdbbbbbbbddrdddddddrddwddddddw@wdebebebeddddddrrdddddwddddddw@wdddddddddddddddddddddwdddiddw@wwwwwwwwwwwwwwwwwwwwwwwwwwwwww", this.model.getHelloWorld().getMessage());
		this.model.loadHelloWorld("5");
		assertEquals("wwwwwwwwwwwwwwwwwwwwwwwwwwwwww@wcbbbbibwddddrrrrrrrrrrrrrrriw@wbbbbbebwddwdddddddddddddddddw@wbbbbbbbwddwrrrrrrrrrrrrrrrrdw@wbbebbbbwddwiddddddddddddddddw@wbbbbbbbwrdwddrrrrrrrrrrrrrrdw@wbbebbbbdddwdddddddddddddddddw@wwwwwwwwwwwwwwwwwwwwwwwwwwwwdw@wbbbbebbbbbbbbbbbbbebbbbbbbbbw@wbbbbebbbbebbbbbbbbebbbbbbbbbw@wbbbbibbbbebbbbibbbbbbbebbbbbw@wwbbbwbbbbbbbbbwbbbbbbbebbbbbw@wdbbbbbebbbbbbbebbbbbbbbbbbbbw@wdwwwwwwwwwwwwwwwwwwwwwwwwwwww@wdddddddrdddddddddddrddrddbbiw@wddddrddrdddrdddddrddddddrrbdw@wddddddddddddrddddddddrdrddbdw@wdddrddrdrddddrddddrddddddrbdw@wdddddddddddddrdddddddddrddedw@wdwwwwwwwwwwwwwwwwwwwwwwwwwwww@wbbbbbbbbbbbbbrbbbbbbbbbbbbbbw@wbbbbbbbbbbbbbdbbbbbbbbbbibbbw@wbbbbbbbbbeeeeeebbbbbbbbbwbbbw@wbbbbbbbbbbbbbbbbbbbbbbbbbbbbw@wbbeeeeeeeeeeeeeeeeeeeeeeebbbw@wbbbbbibbbbbbbbbbbbibbbbbbbbbw@wbbbbbwbbbbbbbbbbbbwbbbbbbbbbw@wbbbbbbbbbbbbbbeeeeeebbbbbbbbw@wbbbbbbbbbbbbbbbbbbbbbbbbbbbpw@wwwwwwwwwwwwwwwwwwwwwwwwwwwwww", this.model.getHelloWorld().getMessage());
	}

	@Test
	public void testGetSprites() {
		assertNotNull(this.model.sprites);
	}

	@Test
	public void testElementList() {
		assertNotNull(this.model.sprites);
	}

	@Test
	public void testGetDwarf() {
		assertNotNull(this.model.dwarfs);
	}

	@Test
	public void testGetElement() {
		assertNotNull(this.model.elements);
		
	}

	@Test
	public void testGetObservable() {
		assertNotNull(this);
	}
	
	
}
